// .docs/src/input/format.tsx
/*
 * @Date: 2024-08-03 08:17:36
 * @Description: Modify here please
 */
import { Input } from "camellia";
import React, { useState } from "react";

const App: React.FC = () => {
  const [value, setValue] = useState("");

  const onChange = (v: string) => {
    setValue(v);
  };

  const onlyAllowNumber = (value: string) => {
    return !value || /^\d+$/.test(value);
  };

  return (
    <>
      <div className="mb-4">
        <Input
          value={value}
          type="number"
          onChange={onChange}
          allowInput={onlyAllowNumber}
          placeholder="只能输入数字"
        />
      </div>
    </>
  );
};

export default App;

// docs/examples/input/format.vue
<!-- eslint-disable no-console -->
<!--
 * @Date: 2024-01-19 15:59:08
 * @Description: Modify here please
-->
<script setup lang="ts">
import { ref } from "vue";

const value = ref(null);

const onChange = (v) => {
  console.log(v);
};

const onInput = (v) => {
  console.log("-----", v);
};

const onlyAllowNumber = (value) => {
  return !value || /^\d+$/.test(value);
};
</script>

<template>
  <div class="mb-4">
    <fb-input v-model="value" @change="onChange" @input="onInput" :allow-input="onlyAllowNumber" placeholder="只能输入数字" />
  </div>
</template>
