// .docs/src/input/size.tsx
/*
 * @Date: 2024-08-03 08:17:36
 * @Description: Modify here please
 */
import { Input } from "camellia";
import React, { useState } from "react";

const App: React.FC = () => {
  const [value, setValue] = useState("");
  return (
    <div style={{ display: "flex" }}>
      <div className="mb-4 mr-4">
        <Input style={{ width: "200px" }} value={value} size="large" />
      </div>
      <div className="mb-4 mr-4">
        <Input style={{ width: "200px" }} value={value} />
      </div>
      <div className="mb-4 mr-4">
        <Input style={{ width: "200px" }} value={value} size="small" />
      </div>
    </div>
  );
};

export default App;

// docs/examples/input/size.vue
<!--
 * @Date: 2024-01-18 20:41:20
 * @Description: Modify here please
-->
<script setup lang="ts">
import { ref } from "vue";

const value = ref(null);
</script>

<template>
  <div style="display: flex">
    <div class="mb-4 mr-4">
      <fb-input style="width: 200px" v-model="value" size="large" />
    </div>
    <div class="mb-4 mr-4">
      <fb-input style="width: 200px" v-model="value" />
    </div>
    <div class="mb-4 mr-4">
      <fb-input style="width: 200px" v-model="value" size="small" />
    </div>
  </div>
</template>
