// .docs/src/input/disabled.tsx
/*
 * @Date: 2024-08-03 08:17:36
 * @Description: Modify here please
 */
import { Input } from "camellia";
import React, { useState } from "react";

const App: React.FC = () => {
  const [value, setValue] = useState("");
  return (
    <>
      <div className="mb-4">
        <Input value={value} placeholder="基本的 input" disabled onChange={(v) => setValue(v)} />
      </div>
    </>
  );
};

export default App;

// docs/examples/button/disabled.vue
<!--
 * @Date: 2024-01-16 19:15:57
 * @Description: Modify here please
-->
<template>
  <div class="mb-4">
    <fb-button disabled>default</fb-button>
    <fb-button type="primary" disabled>Primary</fb-button>
    <fb-button type="success" disabled>Success</fb-button>
    <fb-button type="warning" disabled>Warning</fb-button>
    <fb-button type="danger" disabled>Danger</fb-button>
  </div>
  <div class="mb-4">
    <fb-button plain disabled>default</fb-button>
    <fb-button type="primary" disabled plain>Primary</fb-button>
    <fb-button type="success" disabled plain>Success</fb-button>
    <fb-button type="warning" disabled plain>Warning</fb-button>
    <fb-button type="danger" disabled plain>Danger</fb-button>
  </div>
</template>

<script lang="ts" setup></script>
