// docs/examples/button/basic.vue
<!--
 * @Date: 2024-01-16 19:15:57
 * @Description: Modify here please
-->
<template>
  <div class="mb-4">
    <fb-button>default</fb-button>
    <fb-button type="primary">Primary</fb-button>
    <fb-button type="success">Success</fb-button>
    <fb-button type="warning">Warning</fb-button>
    <fb-button type="danger">Danger</fb-button>
  </div>
  <div class="mb-4">
    <fb-button plain>default</fb-button>
    <fb-button type="primary" plain>Primary</fb-button>
    <fb-button type="success" plain>Success</fb-button>
    <fb-button type="warning" plain>Warning</fb-button>
    <fb-button type="danger" plain>Danger</fb-button>
  </div>
  <div class="mb-4">
    <fb-button ghost>default</fb-button>
    <fb-button type="primary" ghost>Primary</fb-button>
    <fb-button type="success" ghost>Success</fb-button>
    <fb-button type="warning" ghost>Warning</fb-button>
    <fb-button type="danger" ghost>Danger</fb-button>
  </div>
</template>

<script lang="ts" setup></script>

// .docs/src/button/basic.tsx
/*
 * @Date: 2024-08-03 08:17:36
 * @Description: Modify here please
 */
import { Button } from "camelia";
import React from "react";

const App: React.FC = () => {
  return (
    <>
      <div className="mb-4">
        <Button>default</Button>
        <Button type="primary">Primary</Button>
        <Button type="success">Success</Button>
        <Button type="warning">Warning</Button>
        <Button type="danger">Danger</Button>
      </div>
      <div className="mb-4">
        <Button plain>default</Button>
        <Button type="primary" plain>
          Primary
        </Button>
        <Button type="success" plain>
          Success
        </Button>
        <Button type="warning" plain>
          Warning
        </Button>
        <Button type="danger" plain>
          Danger
        </Button>
      </div>
      <div>
        <Button ghost>default</Button>
        <Button type="primary" ghost>
          Primary
        </Button>
        <Button type="success" ghost>
          Success
        </Button>
        <Button type="warning" ghost>
          Warning
        </Button>
        <Button type="danger" ghost>
          Danger
        </Button>
      </div>
    </>
  );
};

export default App;
