// docs/examples/message/basic.vue
<!--
 * @Date: 2024-02-03 21:02:34
 * @Description: Modify here please
-->
<script setup lang="ts">
import { message } from "fish-bubble-design";

const open1 = () => {
  message.info("this is a message.");
};
const open2 = () => {
  message.success("This is a success message");
};
const open3 = () => {
  message.warning("This is a warning message");
};
const open4 = () => {
  message.error("this is a error message.");
};
</script>

<template>
  <div>
    <fb-button plain @click="open2">success</fb-button>
    <fb-button plain @click="open3">warning</fb-button>
    <fb-button plain @click="open1">message</fb-button>
    <fb-button plain @click="open4">error</fb-button>
  </div>
</template>

// .docs/src/button/basic.tsx
/*
 * @Date: 2024-08-03 08:17:36
 * @Description: Modify here please
 */
import { Button } from "camelia";
import React from "react";

const App: React.FC = () => {
  return (
    <>
      <div className="mb-4">
        <Button>default</Button>
        <Button type="primary">Primary</Button>
        <Button type="success">Success</Button>
        <Button type="warning">Warning</Button>
        <Button type="danger">Danger</Button>
      </div>
      <div className="mb-4">
        <Button plain>default</Button>
        <Button type="primary" plain>
          Primary
        </Button>
        <Button type="success" plain>
          Success
        </Button>
        <Button type="warning" plain>
          Warning
        </Button>
        <Button type="danger" plain>
          Danger
        </Button>
      </div>
      <div>
        <Button ghost>default</Button>
        <Button type="primary" ghost>
          Primary
        </Button>
        <Button type="success" ghost>
          Success
        </Button>
        <Button type="warning" ghost>
          Warning
        </Button>
        <Button type="danger" ghost>
          Danger
        </Button>
      </div>
    </>
  );
};

export default App;
