// packages/components/dialog/src/dialog.vue
<!--
 * @Date: 2023-11-27 14:27:58
 * @Description: 基础弹窗
-->
<script setup lang="ts">
import { computed, ref, onMounted, watch } from "vue";
import type { CSSProperties } from "vue";
import type { IDialogProps } from "./type";
import { useZIndex } from "@fish-bubble-design/hooks";
import { isClient, isNumber } from "@fish-bubble-design/shared/utils";
import { useNamespace, useLockscreen } from "@fish-bubble-design/hooks";

import DialogOverlay from "./dialog-overlay.vue";
import DialogContent from "./dialog-content.vue";

defineOptions({
  inheritAttrs: false,
  name: "FbDialog"
});

// 属性
const props = withDefaults(defineProps<IDialogProps>(), {
  modal: true,
  appendTo: "body",
  alignCenter: false,
  closeOnClickModal: false,
  showClose: true,
  lockScroll: true
});

const ns = useNamespace("dialog");

// 事件
const emit = defineEmits({
  close: () => true,
  ["update:open"]: (value: boolean) => typeof value === "boolean"
});

// 弹窗控制器
const visible = ref(false);

const { nextZIndex } = useZIndex();

const contentZIndex = ref<number>(isNumber(props.zIndex) ? props.zIndex : nextZIndex());

// dialog样式
const dialogStyle = computed<CSSProperties>(() => {
  const style: CSSProperties = {};
  if (props.top) {
    style[`margin-top`] = props.top;
  }
  if (props.width) {
    style[`width`] = typeof props.width == "string" ? props.width : `${props.width}px`;
  }
  return style;
});

// 弹窗元素已从 DOM 中移除时调用
const onAfterLeave = () => {
  emit("close");
  emit("update:open", false);
};

// 蒙层点击事件
const onModalClick = () => {
  if (props.closeOnClickModal) {
    onHandleClose();
  }
};

if (props.lockScroll) {
  useLockscreen(visible, ns.b("parent--hidden"));
}

// 关闭弹窗的方法
const onHandleClose = () => {
  function hide(shouldCancel?: boolean) {
    if (shouldCancel) return;
    visible.value = false;
  }
  // 关闭前的回调，会暂停 Dialog 的关闭. 回调函数内执行 done 参数方法的时候才是真正关闭对话框的时候.
  if (props?.beforeClose) {
    props?.beforeClose?.(hide);
  } else {
    visible.value = false;
  }
};

// 初始化
onMounted(() => {
  if (props.open) {
    if (!isClient) return;
    visible.value = true;
  }
});

// 监听变化
watch(
  () => props.open,
  (val) => {
    if (val) {
      if (!isClient) return;
      visible.value = true;
    } else {
      if (visible.value) {
        visible.value = false;
      }
    }
  }
);
</script>

<template>
  <teleport :to="props.appendTo">
    <transition name="dialog-fade" @after-leave="onAfterLeave">
      <DialogOverlay
        v-show="visible"
        :modal="props.modal"
        :overlay-class="props.overlayClass"
        :z-index="contentZIndex"
        :align-center="props.alignCenter"
        @click="onModalClick"
      >
        <div :style="dialogStyle" role="dialog" :class="[ns.b(), ns.is('align-center', props.alignCenter), $attrs?.class]">
          <DialogContent :show-close="props.showClose" @close="onHandleClose" :title="title">
            <!-- 头部 -->
            <template #header>
              <slot name="header" />
            </template>
            <!-- 默认插槽 -->
            <slot />
            <!-- 底部 -->
            <template v-if="$slots?.footer" #footer>
              <slot name="footer" />
            </template>
          </DialogContent>
        </div>
      </DialogOverlay>
    </transition>
  </teleport>
</template>

// packages/components/dialog/Dialog.tsx
/*
 * @Date: 2024-08-03 22:09:25
 * @Description: Modify here please
 */
import React, { useContext, useEffect, useMemo, useState, useRef } from "react";
import classNames from "classnames";
import { CSSTransition } from "react-transition-group";
import { ConfigContext } from "../config-provider";
import { useNamespace, useZIndex } from "@camelia/core/hooks";
import { Close as CloseIcon } from "fish-icons";
import { contains } from "@camelia/core";

import Visible from "../_internal/visible";
import type { IDialogProps } from "./type";
import DialogOverlay from "./DialogOverlay";

const Dialog: React.FC<IDialogProps> = (props) => {
  const {
    top,
    width,
    open,
    transitionName,
    mask = true,
    keyboard = true,
    alignCenter = false,
    closeOnClickMask = true,
    showClose = true,
    duration = 300,
    zIndex,
    overlayClass,
    title,
    className,
    // 内容区
    header,
    children,
    footer,
    // 事件
    onClose,
    afterClose,
    beforeClose
  } = props;

  const { getPrefixCls } = useContext(ConfigContext);

  const ns = useNamespace("dialog", getPrefixCls());

  const [animatedVisible, setAnimatedVisible] = useState<boolean>(false);

  const { currentZIndex } = useZIndex();

  const rootRef = useRef<HTMLDivElement>(null);
  const wrapperRef = useRef<HTMLDivElement>();
  const contentRef = useRef<HTMLDivElement>();

  // dialog Style
  const dialogStyle = useMemo<React.CSSProperties>(() => {
    const style: React.CSSProperties = {};
    if (top) {
      style[`marginTop`] = top;
    }
    if (width) {
      style[`width`] = typeof width == "string" ? width : `${width}px`;
    }
    style[`outline`] = "none";
    // show?
    style[`display`] = animatedVisible ? "block" : "none";
    return style;
  }, [top, width, animatedVisible]);

  // 动画类名
  const motionName = useMemo(() => {
    return transitionName || `dialog-fade`;
  }, [transitionName]);

  // 点击蒙层时
  const onMaskClick = (e: any) => {
    if (closeOnClickMask) {
      onHandleClose(e);
    }
  };

  // 关闭弹窗的方法
  const onHandleClose = (e) => {
    function hide(shouldCancel?: boolean) {
      if (shouldCancel) return;
      onClose?.(e as any);
    }
    // 关闭前的回调，会暂停 Dialog 的关闭. 回调函数内执行 done 参数方法的时候才是真正关闭对话框的时候.
    if (beforeClose) {
      beforeClose?.(hide);
    } else {
      onClose?.(e as any);
    }
  };

  useEffect(() => {
    if (open) {
      setAnimatedVisible(true);
    }
  }, [open]);

  function focusDialogContent() {
    if (!contains(wrapperRef.current, document.activeElement)) {
      contentRef.current?.focus({ preventScroll: true });
    }
  }

  const onEnter = () => {
    // Try to focus
    focusDialogContent();
  };

  // 弹窗元素已从 DOM 中移除时调用
  const onExited = () => {
    // 等待动画结束才才改变状态
    setAnimatedVisible(false);
    if (animatedVisible) {
      requestAnimationFrame(() => {
        afterClose?.();
      });
    }
  };

  return (
    <CSSTransition
      nodeRef={rootRef}
      in={open && animatedVisible}
      timeout={duration}
      classNames={motionName}
      onEnter={onEnter}
      onExited={onExited}
    >
      <DialogOverlay
        mask={mask}
        rootRef={rootRef}
        wrapperRef={wrapperRef}
        overlayClass={overlayClass}
        visible={animatedVisible}
        zIndex={zIndex || currentZIndex}
        keyboard={keyboard}
        style={{ display: animatedVisible ? "block" : "none" }}
        alignCenter={alignCenter}
        onClick={onMaskClick}
        onInternalClose={(e) => onHandleClose(e)}
      >
        <div
          style={dialogStyle}
          ref={contentRef}
          tabIndex={-1}
          role="dialog"
          className={classNames([ns.b(), ns.is("align-center", alignCenter), className])}
        >
          {/* 弹窗关闭按钮 */}
          <Visible visible={showClose}>
            <button className="closeIconbtn" onClick={onHandleClose}>
              <CloseIcon />
            </button>
          </Visible>
          {/* 头部 */}
          <header className={ns.e("header")}>{header || <p className="title">{title}</p>}</header>
          {/* 内容 */}
          <div className={ns.e("body")}>{children || "内容区，请使用插槽添加内容"}</div>
          {/* 底部 */}
          <Visible visible={footer}>
            <footer className={ns.e("footer")}>{footer}</footer>
          </Visible>
        </div>
      </DialogOverlay>
    </CSSTransition>
  );
};

export default Dialog;
