// docs/examples/popover/placement.vue
<template>
  <div class="wrap-base-box">
    <div class="row center">
      <fb-popper trigger="hover" :persistent="false" placement="top-start" :offset="5" :popper-style="{ width: '200px' }">
        <template #default>
          <fb-button plain class="box-item">top-start</fb-button>
        </template>
        <template #popup>
          <div class="popover">
            <div class="content">这就是内容，这就是内容，这就是内容</div>
          </div>
        </template>
      </fb-popper>
      <fb-popper trigger="hover" :persistent="false" placement="top" :offset="5" :popper-style="{ width: '200px' }">
        <template #default>
          <fb-button plain class="box-item">top</fb-button>
        </template>
        <template #popup>
          <div class="popover">
            <div class="content">这就是内容，这就是内容，这就是内容</div>
          </div>
        </template>
      </fb-popper>

      <fb-popper trigger="hover" :persistent="false" placement="top-end" :offset="5" :popper-style="{ width: '200px' }">
        <template #default>
          <fb-button plain class="box-item">top-end</fb-button>
        </template>
        <template #popup>
          <div class="popover">
            <div class="content">这就是内容，这就是内容，这就是内容</div>
          </div>
        </template>
      </fb-popper>
    </div>
    <div class="row">
      <fb-popper trigger="hover" :persistent="false" placement="left-start" :offset="5" :popper-style="{ width: '200px' }">
        <template #default>
          <fb-button plain class="box-item">left-start</fb-button>
        </template>
        <template #popup>
          <div class="popover">
            <div class="content">这就是内容，这就是内容，这就是内容</div>
          </div>
        </template>
      </fb-popper>

      <fb-popper trigger="hover" :persistent="false" placement="right-start" :offset="5" :popper-style="{ width: '200px' }">
        <template #default>
          <fb-button plain class="box-item">right-start</fb-button>
        </template>
        <template #popup>
          <div class="popover">
            <div class="content">这就是内容，这就是内容，这就是内容</div>
          </div>
        </template>
      </fb-popper>
    </div>
    <div class="row">
      <fb-popper trigger="hover" :persistent="false" placement="left" :offset="5" :popper-style="{ width: '200px' }">
        <template #default>
          <fb-button plain class="box-item">left</fb-button>
        </template>
        <template #popup>
          <div class="popover">
            <div class="content">这就是内容，这就是内容，这就是内容</div>
          </div>
        </template>
      </fb-popper>

      <fb-popper trigger="hover" :persistent="false" placement="right" :offset="5" :popper-style="{ width: '200px' }">
        <template #default>
          <fb-button plain class="box-item">right</fb-button>
        </template>
        <template #popup>
          <div class="popover">
            <div class="content">这就是内容，这就是内容，这就是内容</div>
          </div>
        </template>
      </fb-popper>
    </div>
    <div class="row">
      <fb-popper trigger="hover" :persistent="false" placement="left-end" :offset="5" :popper-style="{ width: '200px' }">
        <template #default>
          <fb-button plain class="box-item">left-end</fb-button>
        </template>
        <template #popup>
          <div class="popover">
            <div class="content">这就是内容，这就是内容，这就是内容</div>
          </div>
        </template>
      </fb-popper>
      <fb-popper trigger="hover" :persistent="false" placement="right-end" :offset="5" :popper-style="{ width: '200px' }">
        <template #default>
          <fb-button plain class="box-item">right-end</fb-button>
        </template>
        <template #popup>
          <div class="popover">
            <div class="content">这就是内容，这就是内容，这就是内容</div>
          </div>
        </template>
      </fb-popper>
    </div>
    <div class="row center">
      <fb-popper trigger="hover" :persistent="false" placement="bottom-start" :offset="5" :popper-style="{ width: '200px' }">
        <template #default>
          <fb-button plain class="box-item">bottom-start</fb-button>
        </template>
        <template #popup>
          <div class="popover">
            <div class="content">这就是内容，这就是内容，这就是内容</div>
          </div>
        </template>
      </fb-popper>
      <fb-popper trigger="hover" :persistent="false" placement="bottom" :offset="5" :popper-style="{ width: '200px' }">
        <template #default>
          <fb-button plain class="box-item">bottom</fb-button>
        </template>
        <template #popup>
          <div class="popover">
            <div class="content">这就是内容，这就是内容，这就是内容</div>
          </div>
        </template>
      </fb-popper>
      <fb-popper trigger="hover" :persistent="false" placement="bottom-end" :offset="5" :popper-style="{ width: '200px' }">
        <template #default>
          <fb-button plain class="box-item">bottom-end</fb-button>
        </template>
        <template #popup>
          <div class="popover">
            <div class="content">这就是内容，这就是内容，这就是内容</div>
          </div>
        </template>
      </fb-popper>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.wrap-base-box {
  width: 600px;
}
.wrap-base-box .row {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.wrap-base-box .center {
  justify-content: center;
}
.wrap-base-box .box-item {
  margin-top: 10px;
}

.popover {
  padding: 12px;
  background-color: white;
  border: 1px solid #e4e7ed;
  box-shadow: 0px 0px 12px rgba(0, 0, 0, 0.12);
  border-radius: 4px;
  .title {
    color: #303133;
    font-size: 16px;
    margin-bottom: 12px;
  }
  .content {
    color: #606266;
    font-size: 14px;
  }
}
</style>

// .docs/src/tooltip/placement.tsx
/*
 * @Date: 2024-08-31 23:14:18
 * @Description: Modify here please
 */
import React from 'react';
import { Tooltip, Button } from 'camelia';

const text = <span>prompt text prompt text </span>;

const App: React.FC = () => (
  <div className="wrap-base-box">
    <div className="row center">
      <Tooltip placement="top-start" title={text}>
        <Button plain className="box-item">top-start</Button>
      </Tooltip>
      <Tooltip placement="top" title={text}>
        <Button plain className="box-item">top</Button>
      </Tooltip>
      <Tooltip placement="top-end" title={text}>
        <Button plain className="box-item">top-end</Button>
      </Tooltip>
    </div>
    <div className="row">
     <Tooltip placement="left-start" title={text}>
        <Button plain className="box-item">left-start</Button>
      </Tooltip>
      <Tooltip placement="right-start" title={text}>
        <Button plain className="box-item">right-start</Button>
      </Tooltip>
    </div>
    <div className="row">
      <Tooltip placement="left" title={text}>
        <Button plain className="box-item">left</Button>
      </Tooltip>
      <Tooltip placement="right" title={text}>
        <Button plain className="box-item">right</Button>
      </Tooltip>
    </div>
    <div className="row">
      <Tooltip placement="left-end" title={text}>
        <Button plain className="box-item">left-end</Button>
      </Tooltip>
      <Tooltip placement="right-end" title={text}>
        <Button  plain className="box-item">right-end</Button>
      </Tooltip>
    </div>
    <div className="row center">
       <Tooltip placement="bottom-start" title={text}>
          <Button  plain className="box-item">bottom-start</Button>
        </Tooltip>
        <Tooltip placement="bottom" title={text}>
          <Button  plain className="box-item">bottom</Button>
        </Tooltip>
        <Tooltip placement="bottom-end" title={text}>
          <Button plain className="box-item">bottom-end</Button>
        </Tooltip>
    </div>
  </div>
);

export default App
