// packages/components/_internal/wave/index.tsx
/*
 * @Date: 2024-07-28 15:19:45
 * @Description: 波浪效果组件
 */
import React, { useContext, useRef, useState, useImperativeHandle } from "react";
import { ConfigContext } from "../../config-provider";
import { useNamespace } from "@fish-remix/hooks";
import classNames from "classnames";

export interface WaveRef {
  play: () => void;
}

type WaveProps = {};

let animationTimerId: number | null = null;

/** 波浪效果组件 */
const Wave = React.forwardRef<WaveRef, WaveProps>((_, ref) => {
  const { getPrefixCls } = useContext(ConfigContext);

  const ns = useNamespace("base-wave", getPrefixCls());

  const selfRef = useRef<HTMLDivElement | null>(null);
  // 主动控制模式
  const [active, setActive] = useState(false);

  const play = () => {
    if (animationTimerId !== null) {
      window.clearTimeout(animationTimerId);
      setActive(false);
      animationTimerId = null;
    }
    requestAnimationFrame(() => {
      setActive(true);
      animationTimerId = window.setTimeout(() => {
        setActive(false);
        animationTimerId = null;
      }, 1000);
    });
  };

  useImperativeHandle(ref, () => ({
    play
  }));

  return <div ref={selfRef} aria-hidden className={classNames(ns.b(), active && `is-active`)} />;
});

export default Wave;

// packages/components/_internal/wave/src/wave.vue
<!--
 * @Date: 2024-01-04 20:24:45
 * @Description: 波浪效果组件
-->
<script setup lang="ts">
import { ref, onBeforeUnmount, nextTick } from "vue";
import { useNamespace } from "@fish-bubble-design/hooks";

defineOptions({
  name: "BaseWave"
});

const ns = useNamespace("base-wave");

const selfRef = ref<HTMLElement | null>(null);
// 主动控制模式
const activeRef = ref(false);
let animationTimerId: number | null = null;

onBeforeUnmount(() => {
  if (animationTimerId !== null) {
    window.clearTimeout(animationTimerId);
  }
});

const play = () => {
  if (animationTimerId !== null) {
    window.clearTimeout(animationTimerId);
    activeRef.value = false;
    animationTimerId = null;
  }
  void nextTick(() => {
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    void selfRef.value?.offsetHeight;
    activeRef.value = true;
    animationTimerId = window.setTimeout(() => {
      activeRef.value = false;
      animationTimerId = null;
    }, 1000);
  });
};

defineExpose({ play });
</script>

<template>
  <div ref="selfRef" aria-hidden :class="[ns.b(), activeRef && `is-active`]" />
</template>
