// packages/components/input/src/input.vue
<!--
 * @Date: 2023-12-23 17:51:35
 * @Description: Modify here please
-->
<script setup lang="ts">
import { ref, computed, shallowRef, watch, nextTick, onMounted, useAttrs } from "vue";
import type { StyleValue } from "vue";
import { useNamespace } from "@fish-bubble-design/hooks";
import { isNil } from "@fish-bubble-design/shared/utils";
import { CircleCloseFilled } from "@fish-bubble/icons";

import { useFocusController } from "@fish-bubble-design/hooks";
import BaseWave from "../../_internal/wave/src/wave.vue";

import type { InputProps, InputEmits } from "./type";
type TargetElement = HTMLInputElement | HTMLTextAreaElement;

const emit = defineEmits<InputEmits>();

const rawAttrs = useAttrs();

defineOptions({ name: "FbInput", inheritAttrs: false });

const props = withDefaults(defineProps<InputProps>(), {
  placeholder: "请输入",
  type: "text",
  wave: true
});

const nsInput = useNamespace("input");
const nsTextarea = useNamespace("textarea");

const inputRef = shallowRef<HTMLInputElement>();
const textareaRef = shallowRef<HTMLInputElement>();

const _ref = computed(() => inputRef.value || textareaRef.value);

const { wrapperRef, isFocused, handleFocus, handleBlur } = useFocusController(_ref);

const hovering = ref(false);
const isComposing = ref(false);

const nativeInputValue = computed(() => (isNil(props.modelValue) ? "" : String(props.modelValue)));

const wrapperKls = computed(() => {
  if (props.type !== "textarea") {
    return [nsInput.b(), nsInput.m(props.size), nsInput.is("focus", isFocused.value), nsInput.is("disabled", inputDisabled.value), rawAttrs.class];
  }
  return [nsTextarea.b(), nsInput.is("focus", isFocused.value), rawAttrs.class];
});

const wrapperStyle = computed<StyleValue>(() => [rawAttrs.style as StyleValue]);

// todo useFormDisabled
const inputDisabled = computed(() => props.disabled);
// 何时显示清除图标
const showClear = computed(() => props.clearable && !props.disabled && !props.readonly && !!nativeInputValue.value && (isFocused.value || hovering.value));

function allowInput(value: string): boolean {
  const { allowInput } = props;
  if (typeof allowInput === "function") {
    return allowInput(value);
  }
  return true;
}

const handleInput = async (event: Event) => {
  const { value } = event.target as TargetElement;

  const isIncomingValueValid = allowInput(value);

  // 在合成过程中不应发出输入
  if (isComposing.value) return;

  if (value === nativeInputValue.value) {
    setNativeInputValue();
    return;
  }

  if (isIncomingValueValid) {
    emit("update:modelValue", value);
    emit("input", value);
  }

  // 确保本地输入值得到控制
  await nextTick();
  setNativeInputValue();
};

// 设置值
const setNativeInputValue = () => {
  // 输入口的节点
  const input = _ref.value;
  const formatterValue = nativeInputValue.value;
  if (!input || input.value === formatterValue) return;
  // 给节点赋值
  input.value = formatterValue;
};

const handleCompositionEnd = (event: CompositionEvent) => {
  if (isComposing.value) {
    isComposing.value = false;
    handleInput(event);
  }
};

const clear = () => {
  emit("update:modelValue", "");
  emit("input", "");
};

const handleChange = (event: Event) => {
  emit("change", (event.target as TargetElement).value);
};

watch(nativeInputValue, () => setNativeInputValue());

const focus = async () => {
  await nextTick();
  _ref.value?.focus();
};

const blur = () => _ref.value?.blur();

onMounted(() => {
  setNativeInputValue();
});

const handleMouseLeave = (evt: MouseEvent) => {
  hovering.value = false;
};

const handleMouseEnter = (evt: MouseEvent) => {
  hovering.value = true;
};

defineExpose({
  /** @description HTML element, input or textarea */
  ref: _ref,
  /** @description HTML input element native method */
  focus,
  /** @description HTML input element native method */
  blur,
  /** @description clear input value */
  clear
});
</script>

<template>
  <div :class="wrapperKls" :style="wrapperStyle" ref="wrapperRef" @mouseenter="handleMouseEnter" @mouseleave="handleMouseLeave" v-if="type !== 'textarea'">
    <!-- 前缀 -->
    <span v-if="$slots.prefix" :class="nsInput.e('prefix')">
      <slot name="prefix" />
    </span>
    <input
      ref="inputRef"
      :class="[nsInput.e('inner')]"
      :style="inputStyle"
      :disabled="inputDisabled"
      :maxlength="maxlength"
      :readonly="readonly"
      :autofocus="autofocus"
      :placeholder="placeholder"
      :type="type"
      @compositionstart="() => (isComposing = true)"
      @compositionend="handleCompositionEnd"
      @input="handleInput"
      @change="handleChange"
      @focus="handleFocus"
      @blur="handleBlur"
    />
    <span :class="nsInput.e('suffix')" v-if="$slots.suffix || showClear">
      <template v-if="!showClear">
        <slot name="suffix" />
      </template>
      <!-- 关闭按钮 -->
      <CircleCloseFilled v-if="showClear" class="closeIcon" @click="clear" />
    </span>

    <!-- 波浪 -->
    <BaseWave v-if="wave" />
  </div>
  <div :class="wrapperKls" :style="wrapperStyle" ref="wrapperRef" v-if="type == 'textarea'">
    <textarea
      ref="textareaRef"
      :class="nsTextarea.e('inner')"
      :style="inputStyle"
      :disabled="inputDisabled"
      :readonly="readonly"
      :autofocus="autofocus"
      :placeholder="placeholder"
      @compositionstart="() => (isComposing = true)"
      @compositionend="handleCompositionEnd"
      @input="handleInput"
      @focus="handleFocus"
      @blur="handleBlur"
    />
    <!-- 波浪 -->
    <BaseWave v-if="wave" />
  </div>
</template>

// packages/components/input/input.tsx
/*
 * @Date: 2024-08-05 22:16:34
 * @Description: Modify here please
 */
import React, { useContext, useRef, useMemo, useState, useEffect, useImperativeHandle } from "react";
import classNames from "classnames";
import { CircleCloseFilled } from "fish-icons";

import { useNamespace, useFocusController } from "@fish-remix/hooks";
import { isNil } from "@fish-remix/shared/utils";
import { nextTick } from "@fish-remix/core";

import { ConfigContext } from "../config-provider";
import Visible from "../_internal/visible";
import BaseWave from "../_internal/wave";
import type { InputProps, InputRef } from "./type";

const Input = React.forwardRef<InputRef, InputProps>((props, ref) => {
  const {
    placeholder = "请输入",
    type = "text",
    wave = true,
    value,
    disabled,
    size,
    className,
    autoFocus,
    style,
    clearable,
    readOnly,
    prefix,
    suffix,
    inputStyle,
    maxLength,
    onChange,
    onClear
  } = props;

  const { getPrefixCls } = useContext(ConfigContext);

  const nsInput = useNamespace("input", getPrefixCls());
  const nsTextarea = useNamespace("textarea", getPrefixCls());

  const inputRef = useRef<HTMLInputElement>();
  const textareaRef = useRef<HTMLInputElement>();

  const _ref = type !== "textarea" ? inputRef : textareaRef;

  const { wrapperRef, isFocused, handleFocus, handleBlur } = useFocusController(_ref);

  const [hovering, setGovering] = useState<boolean>(false);
  const isComposing = useRef<boolean>(false);

  // 初始值
  const nativeInputValue = useMemo(() => (isNil(value) ? "" : String(value)), [value]);

  // 外层class
  const wrapperKls = useMemo(() => {
    if (props.type !== "textarea") {
      return [
        nsInput.b(),
        nsInput.m(props.size),
        nsInput.is("focus", isFocused),
        nsInput.is("disabled", disabled),
        className
      ];
    }
    return [nsTextarea.b(), nsInput.is("focus", isFocused), className];
  }, [type, size, isFocused, className, disabled]);

  // 何时显示清除图标
  const showClear = clearable && !disabled && !readOnly && !!nativeInputValue && (isFocused || hovering);

  // 校验当前的输入是否合法
  const allowInput = (value: string): boolean => {
    const { allowInput } = props;
    if (typeof allowInput === "function") {
      return allowInput(value);
    }
    return true;
  };

  // 输入框值变化
  const handleInput = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const { value } = event.target as any;

    const isIncomingValueValid = allowInput(value);

    // 在合成过程中不应发出输入
    if (isComposing.current) return;

    if (value === nativeInputValue) {
      setNativeInputValue();
      return;
    }

    if (isIncomingValueValid) {
      onChange?.(value);
    }

    // 确保本地输入值得到控制
    await nextTick();

    setNativeInputValue();
  };

  // 设置值
  const setNativeInputValue = () => {
    // 输入口的节点
    const input = _ref.current;
    const formatterValue = nativeInputValue;
    if (!input || input.value === formatterValue) return;
    // 给节点赋值
    input.value = formatterValue;
  };

  const handleCompositionEnd = (event: any) => {
    if (isComposing) {
      isComposing.current = false;
      handleInput(event);
    }
  };

  const handleMouseLeave = (_) => {
    setGovering(false);
  };

  const handleMouseEnter = (_) => {
    setGovering(true);
  };

  // 点击清除按钮
  const handleReset = () => {
    _ref.current.value = "";
    onChange?.("");
  };

  useEffect(() => {
    setNativeInputValue();
  }, [nativeInputValue]);

  // 主动获取焦点方法
  const focus = async () => {
    await nextTick();
    _ref.current?.focus();
  };

  const blur = () => _ref.current?.blur();

  useImperativeHandle(ref, () => ({
    focus,
    blur
  }));

  return (
    <>
      <Visible visible={type !== "textarea"}>
        <div
          className={classNames(...wrapperKls)}
          style={style}
          ref={wrapperRef}
          onMouseEnter={handleMouseEnter}
          onMouseLeave={handleMouseLeave}
        >
          {/* 前缀 */}
          {prefix && <span className={nsInput.e("prefix")}>{prefix}</span>}
          <input
            ref={inputRef}
            className={nsInput.e("inner")}
            style={inputStyle}
            disabled={disabled}
            maxLength={maxLength}
            readOnly={readOnly}
            autoFocus={autoFocus}
            placeholder={placeholder}
            type={type}
            onCompositionStart={() => (isComposing.current = true)}
            onCompositionEnd={handleCompositionEnd}
            onInput={handleInput}
            onFocus={handleFocus}
            onBlur={handleBlur}
          />
          <Visible visible={suffix || showClear}>
            <span className={nsInput.e("suffix")}>
              <Visible visible={!showClear}>{suffix}</Visible>
              {/* 关闭按钮 */}
              <Visible visible={showClear}>
                {
                  <CircleCloseFilled
                    className="closeIcon"
                    onClick={() => {
                      handleReset();
                      onClear?.();
                    }}
                  />
                }
              </Visible>
            </span>
          </Visible>
          {/* 波浪 */}
          {wave && <BaseWave />}
        </div>
      </Visible>
    </>
  );
});

export default Input;
