// packages/components/tag/tag.tsx
/*
 * @Date: 2024-08-03 20:51:37
 * @Description: Modify here please
 */
import React, { useContext, useMemo } from "react";
import classNames from "classnames";
import { ConfigContext } from "../config-provider";
import { useNamespace } from "@fish-remix/hooks";
import { Close } from "fish-icons";
import Visible from "../_internal/visible";

import type { ComponentSize } from "@fish-remix/core";

export interface ITagProps {
  /** 按钮类型 */
  type?: "" | "success" | "warning" | "danger" | "info";
  /** 幽灵属性，使按钮背景透明 */
  effect?: "dark" | "light" | "plain";
  /** 大小 */
  size?: ComponentSize;
  /** Tag 是否为圆形 */
  round?: boolean;
  /** 是否可关闭 */
  closable?: boolean;
  /** 语义化结构className */
  className?: string;
  /** 自定义背景色 */
  color?: string;
  icon?: React.ReactNode;
  /** 内容 */
  children?: React.ReactNode;
  /** 关闭时的回调 */
  onClose?: (e: React.MouseEvent<HTMLElement, MouseEvent>) => void;
  onClick?: (e: React.MouseEvent<HTMLElement, MouseEvent>) => void;
}

const Tag: React.FC<ITagProps> = (props) => {
  const { icon, children, closable, type = "", effect = "light", round, size, color, className } = props;
  const { getPrefixCls } = useContext(ConfigContext);

  const ns = useNamespace("tag", getPrefixCls());

  const containerKls = useMemo(() => {
    return [
      ns.b(),
      ns.is("closable", closable),
      ns.m(type),
      ns.m(size),
      ns.m(effect),
      ns.is("round", round),
      ns.is("color", !!color)
    ];
  }, [type, effect, closable, round, size, color]);

  const containerStyle = useMemo(() => {
    return color ? { backgroundColor: color } : {};
  }, [color]);

  // methods
  const handleClose = (event: React.MouseEvent<HTMLElement, MouseEvent>) => {
    event.stopPropagation();
    props.onClose?.(event);
  };

  const handleClick = (event: React.MouseEvent<HTMLElement, MouseEvent>) => {
    event.stopPropagation();
    props.onClick?.(event);
  };

  return (
    <span className={classNames(...containerKls, className)} style={containerStyle} onClick={handleClick}>
      {icon}
      <span className={ns.e("content")}>{children}</span>
      <Visible visible={closable}>
        <Close className={ns.e("close")} onClick={handleClose as any} />
      </Visible>
    </span>
  );
};

export default Tag;

// packages/components/tag/src/tag.vue
<!--
 * @Date: 2024-02-02 17:38:33
 * @Description: Modify here please
-->
<template>
  <span :class="containerKls" :style="containerStyle" @click="handleClick">
    <slot name="icon" />
    <span :class="ns.e('content')">
      <slot />
    </span>
    <Close v-if="closable" :class="ns.e('close')" @click.stop="handleClose" />
  </span>
</template>

<script lang="ts" setup>
import { computed } from "vue";
import { Close } from "@fish-bubble/icons";
import { useNamespace } from "@fish-bubble-design/hooks";
import type { ComponentSize } from "@fish-bubble-design/core";

interface ITagProps {
  /** 按钮类型 */
  type?: "" | "success" | "warning" | "danger" | "info";
  /** 幽灵属性，使按钮背景透明 */
  effect?: "dark" | "light" | "plain";
  /** 大小 */
  size?: ComponentSize;
  /** Tag 是否为圆形 */
  round?: boolean;
  /** 是否可关闭 */
  closable?: boolean;
  /** 自定义背景色 */
  color?: string;
}

defineOptions({
  name: "FbTag"
});

const props = withDefaults(defineProps<ITagProps>(), {
  type: "",
  effect: "light"
});

const emit = defineEmits({
  close: (evt: MouseEvent) => evt instanceof MouseEvent,
  click: (evt: MouseEvent) => evt instanceof MouseEvent
});

const ns = useNamespace("tag");

const containerKls = computed(() => {
  const { type, effect, closable, round, size, color } = props;
  return [ns.b(), ns.is("closable", closable), ns.m(type), ns.m(size), ns.m(effect), ns.is("round", round), ns.is("color", !!color)];
});

const containerStyle = computed(() => {
  return props.color ? { backgroundColor: props.color } : {};
});

// methods
const handleClose = (event: MouseEvent) => {
  emit("close", event);
};

const handleClick = (event: MouseEvent) => {
  emit("click", event);
};
</script>
