// docs/examples/input/basic.vue
<!--
 * @Date: 2024-01-19 15:59:08
 * @Description: Modify here please
-->
<script setup lang="ts">
import { ref } from "vue";

const value = ref("hahahh");
</script>

<template>
  <div class="mb-4">
    <fb-input v-model:model-value="value" placeholder="基本的 input" clearable />
  </div>
</template>

// .docs/src/input/basic.tsx
/*
 * @Date: 2024-08-03 08:17:36
 * @Description: Modify here please
 */
import { Input } from "camelia";

import React, { useState } from "react";

const App: React.FC = () => {
  const [value, setValue] = useState("");
  return (
    <>
      <div className="mb-4">
        <Input
          value={value}
          placeholder="基本的 input"
          onPressEnter={(e) => console.log(e)}
          clearable
          onChange={(v) => setValue(v)}
        />
      </div>
    </>
  );
};

export default App;
