// docs/examples/button/size.vue
<!--
 * @Date: 2024-01-16 19:15:57
 * @Description: Modify here please
-->
<template>
  <div class="mb-4">
    <fb-button type="primary" size="large">Primary</fb-button>
    <fb-button type="warning" loading>Warning</fb-button>
    <fb-button type="success" size="small">Success</fb-button>
  </div>
</template>

<script lang="ts" setup></script>

// .docs/src/input/size.tsx
/*
 * @Date: 2024-08-03 08:17:36
 * @Description: Modify here please
 */
import { Input } from "camellia";
import React, { useState } from "react";

const App: React.FC = () => {
  const [value, setValue] = useState("");
  return (
    <div style={{ display: "flex" }}>
      <div className="mb-4 mr-4">
        <Input style={{ width: "200px" }} value={value} size="large" />
      </div>
      <div className="mb-4 mr-4">
        <Input style={{ width: "200px" }} value={value} />
      </div>
      <div className="mb-4 mr-4">
        <Input style={{ width: "200px" }} value={value} size="small" />
      </div>
    </div>
  );
};

export default App;
